tls:
  certificates:
    - certFile: "/etc/traefik/certs/local-cert.pem"
      keyFile: "/etc/traefik/certs/local-key.pem"
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/local-cert.pem"
        keyFile: "/etc/traefik/certs/local-key.pem"
