server:
  port: 8082

spring:
  application:
    name: payment-worck
  
  rabbitmq:
    addresses: amqp://guest:guest@rabbitmq:5672

logging:
  level:
    org.springframework: INFO
    dev.payment-worck: DEBUG
