server:
  port: 8083

spring:
  application:
    name: payment-worker
  
  rabbitmq:
    addresses: amqp://guest:guest@rabbitmq:5672

logging:
  level:
    org.springframework: INFO
    dev.payment_worker: DEBUG
